import type {
  SolutionComponentSummary,
  SolutionDependencyReport,
  SolutionLayer,
  SolutionSummary,
  SolutionWebResourceCandidate,
} from "@/core/dataverse/schemas"

export const mockSolutions: SolutionSummary[] = [
  {
    id: "solution-core",
    uniqueName: "CoreCustomizations",
    friendlyName: "Core Customizations",
    version: "1.4.0.0",
    isManaged: false,
    isVisible: true,
    publisherId: "publisher-contoso",
    publisherName: "Contoso",
    publisherUniqueName: "contoso",
    publisherPrefix: "new",
    createdOn: "2026-06-10T08:15:00Z",
    modifiedOn: "2026-06-17T09:30:00Z",
    componentCount: 11,
  },
  {
    id: "solution-sales",
    uniqueName: "SalesManaged",
    friendlyName: "Sales Managed",
    version: "3.2.1.0",
    isManaged: true,
    isVisible: true,
    publisherId: "publisher-microsoft",
    publisherName: "Microsoft",
    publisherUniqueName: "microsoft",
    publisherPrefix: "msdyn",
    createdOn: "2026-05-29T12:00:00Z",
    modifiedOn: "2026-06-14T11:45:00Z",
    componentCount: 5,
  },
]

export const mockSolutionComponents: SolutionComponentSummary[] = [
  {
    id: "component-account-table",
    solutionId: "solution-core",
    objectId: "11111111-1111-1111-1111-111111111111",
    componentType: 1,
    componentTypeLabel: "Table",
    group: "Tables",
    displayName: "Account",
    logicalName: "account",
    schemaName: "Account",
    isManaged: false,
    modifiedOn: "2026-06-17T09:25:00Z",
    rootComponentBehavior: 0,
    rootComponentBehaviorLabel: "Include subcomponents",
    layerName: "account",
  },
  {
    id: "component-account-form",
    solutionId: "solution-core",
    objectId: "22222222-2222-2222-2222-222222222222",
    componentType: 60,
    componentTypeLabel: "System Form",
    group: "Forms",
    displayName: "Account Main",
    logicalName: "account",
    isManaged: false,
    modifiedOn: "2026-06-17T09:28:00Z",
    layerName: "Account Main",
  },
  {
    id: "component-account-view",
    solutionId: "solution-core",
    objectId: "33333333-3333-3333-3333-333333333333",
    componentType: 26,
    componentTypeLabel: "View",
    group: "Views",
    displayName: "Active Accounts",
    logicalName: "account",
    isManaged: false,
    modifiedOn: "2026-06-16T15:10:00Z",
    layerName: "Active Accounts",
  },
  {
    id: "component-account-script",
    solutionId: "solution-core",
    objectId: "44444444-4444-4444-4444-444444444444",
    componentType: 61,
    componentTypeLabel: "Web Resource",
    group: "Web Resources",
    displayName: "new_/scripts/account-form.js",
    logicalName: "new_/scripts/account-form.js",
    schemaName: "new_/scripts/account-form.js",
    isManaged: false,
    modifiedOn: "2026-06-17T09:30:00Z",
    relatedEntityLogicalName: "webresource",
    relatedRecordUrl: "https://example.crm.dynamics.com/main.aspx?pagetype=entityrecord&etn=webresource&id=44444444-4444-4444-4444-444444444444",
    layerName: "new_/scripts/account-form.js",
  },
  {
    id: "component-theme-css",
    solutionId: "solution-core",
    objectId: "55555555-5555-5555-5555-555555555555",
    componentType: 61,
    componentTypeLabel: "Web Resource",
    group: "Web Resources",
    displayName: "new_/styles/account.css",
    logicalName: "new_/styles/account.css",
    schemaName: "new_/styles/account.css",
    isManaged: false,
    modifiedOn: "2026-06-15T17:35:00Z",
    relatedEntityLogicalName: "webresource",
    relatedRecordUrl: "https://example.crm.dynamics.com/main.aspx?pagetype=entityrecord&etn=webresource&id=55555555-5555-5555-5555-555555555555",
    layerName: "new_/styles/account.css",
  },
  {
    id: "component-long-web-resource",
    solutionId: "solution-core",
    objectId: "88888888-4444-4444-4444-888888888888",
    componentType: 61,
    componentTypeLabel: "Web Resource",
    group: "Web Resources",
    displayName:
      "new_/ClientApps/AccountsView/EnhancedTemplate/Resources/scripts/accounts-view-grid-controller.js",
    logicalName:
      "new_/ClientApps/AccountsView/EnhancedTemplate/Resources/scripts/accounts-view-grid-controller.js",
    schemaName:
      "new_/ClientApps/AccountsView/EnhancedTemplate/Resources/scripts/accounts-view-grid-controller.js",
    isManaged: false,
    modifiedOn: "2026-06-21T12:45:00Z",
    relatedEntityLogicalName: "webresource",
    relatedRecordUrl:
      "https://example.crm.dynamics.com/main.aspx?pagetype=entityrecord&etn=webresource&id=88888888-4444-4444-4444-888888888888",
    layerName:
      "new_/ClientApps/AccountsView/EnhancedTemplate/Resources/scripts/accounts-view-grid-controller.js",
  },
  {
    id: "component-env-definition",
    solutionId: "solution-core",
    objectId: "66666666-6666-6666-6666-666666666666",
    componentType: 380,
    componentTypeLabel: "Environment Variable Definition",
    group: "Environment Variables",
    displayName: "new_ServiceEndpoint",
    schemaName: "new_ServiceEndpoint",
    isManaged: false,
    modifiedOn: "2026-06-12T14:20:00Z",
    relatedEntityLogicalName: "environmentvariabledefinition",
    layerName: "new_ServiceEndpoint",
  },
  {
    id: "component-priority-choice",
    solutionId: "solution-core",
    objectId: "99999999-9999-4999-8999-999999999999",
    componentType: 9,
    componentTypeLabel: "Choice",
    group: "Choices",
    displayName: "Priority",
    logicalName: "new_priority",
    schemaName: "new_priority",
    isManaged: false,
    modifiedOn: "2026-06-13T10:15:00Z",
    layerName: "new_priority",
  },
  {
    id: "component-main-sitemap",
    solutionId: "solution-core",
    objectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    componentType: 62,
    componentTypeLabel: "Site Map",
    group: "Site Maps",
    displayName: "Sales Hub Site Map",
    logicalName: "saleshub",
    isManaged: false,
    modifiedOn: "2026-06-13T11:05:00Z",
    relatedEntityLogicalName: "sitemap",
    layerName: "Sales Hub Site Map",
  },
  {
    id: "component-command-control",
    solutionId: "solution-core",
    objectId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    componentType: 64,
    componentTypeLabel: "Complex Control",
    group: "Custom Controls",
    displayName: "Command Bar Component Library",
    logicalName: "new_commandbar_components",
    isManaged: false,
    modifiedOn: "2026-06-13T12:30:00Z",
    relatedEntityLogicalName: "customcontrol",
    layerName: "Command Bar Component Library",
  },
  {
    id: "component-inspection-app",
    solutionId: "solution-core",
    objectId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    componentType: 300,
    componentTypeLabel: "Canvas App",
    group: "Apps",
    displayName: "Inspection Canvas App",
    logicalName: "inspection_canvas_app",
    isManaged: false,
    modifiedOn: "2026-06-14T11:45:00Z",
    relatedEntityLogicalName: "canvasapp",
    layerName: "Inspection Canvas App",
  },
  {
    id: "component-managed-app",
    solutionId: "solution-sales",
    objectId: "77777777-7777-7777-7777-777777777777",
    componentType: 300,
    componentTypeLabel: "Canvas App",
    group: "Apps",
    displayName: "Sales Review",
    logicalName: "sales_review",
    isManaged: true,
    modifiedOn: "2026-06-14T11:45:00Z",
    layerName: "Sales Review",
  },
]

export const mockWebResourceCandidates: SolutionWebResourceCandidate[] = [
  {
    id: "44444444-4444-4444-4444-444444444444",
    name: "new_/scripts/account-form.js",
    displayName: "Account form script",
    type: "js",
    typeCode: 3,
    isManaged: false,
    inSolution: true,
    modifiedOn: "2026-06-17T09:30:00Z",
  },
  {
    id: "88888888-8888-8888-8888-888888888888",
    name: "new_/scripts/contact-form.js",
    displayName: "Contact form script",
    type: "js",
    typeCode: 3,
    isManaged: false,
    inSolution: false,
    modifiedOn: "2026-06-15T13:20:00Z",
  },
  {
    id: "99999999-9999-9999-9999-999999999999",
    name: "new_/html/dialog.html",
    displayName: "Dialog HTML",
    type: "html",
    typeCode: 1,
    isManaged: false,
    inSolution: false,
    modifiedOn: "2026-06-13T10:05:00Z",
  },
  {
    id: "preview-add-existing-error",
    name: "new_/scripts/browser-preview-error.js",
    displayName: "Browser preview error case",
    type: "js",
    typeCode: 3,
    isManaged: false,
    inSolution: false,
    modifiedOn: "2026-06-12T08:10:00Z",
  },
  {
    id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    name: "msdyn_/scripts/platform.js",
    displayName: "Platform script",
    type: "js",
    typeCode: 3,
    isManaged: false,
    inSolution: false,
    modifiedOn: "2026-06-11T10:05:00Z",
  },
  {
    id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    name: "new_/scripts/managed.js",
    displayName: "Managed script",
    type: "js",
    typeCode: 3,
    isManaged: true,
    inSolution: false,
    modifiedOn: "2026-06-10T10:05:00Z",
  },
]

export const mockDependencyReport: SolutionDependencyReport = {
  required: [
    {
      id: "dependency-required-account",
      dependencyType: 2,
      dependencyTypeLabel: "Published",
      dependentComponentType: 61,
      dependentComponentTypeLabel: "Web Resource",
      dependentComponentObjectId: "44444444-4444-4444-4444-444444444444",
      requiredComponentType: 1,
      requiredComponentTypeLabel: "Table",
      requiredComponentObjectId: "11111111-1111-1111-1111-111111111111",
    },
  ],
  dependents: [
    {
      id: "dependency-dependent-form",
      dependencyType: 2,
      dependencyTypeLabel: "Published",
      dependentComponentType: 60,
      dependentComponentTypeLabel: "System Form",
      dependentComponentObjectId: "22222222-2222-2222-2222-222222222222",
      requiredComponentType: 61,
      requiredComponentTypeLabel: "Web Resource",
      requiredComponentObjectId: "44444444-4444-4444-4444-444444444444",
    },
  ],
  deleteBlockers: [],
}

export const mockSolutionLayers: SolutionLayer[] = [
  {
    id: "layer-active",
    name: "Active",
    componentName: "new_/scripts/account-form.js",
    solutionName: "Active",
    publisherName: "Unmanaged",
    order: 2,
    overwriteTime: "2026-06-17T09:30:00Z",
  },
  {
    id: "layer-core",
    name: "Core Customizations",
    componentName: "new_/scripts/account-form.js",
    solutionName: "Core Customizations",
    publisherName: "Contoso",
    order: 1,
    overwriteTime: "2026-06-10T08:15:00Z",
  },
]
